---
- name: Add ngnix signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  register: nginx_key_installed

- name: Add ngnix deb-src repo
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ trusty nginx' state=present
  when: nginx_key_installed|success

- name: Add ngnix deb repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present
  when: nginx_key_installed|success
  register: nginx_repo_installed

- name: Install nginx
  apt: name=nginx update_cache=yes state=latest
  when: nginx_repo_installed|success
  register: nginx_installed
